### ISSUE TITLE
only new installation ok

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#212]
After havung problems with updating from 3.05 to 3.06, I installed new after uninstalling and cleaning db. Installation now ok. Will try more.

**Comment by JKoelman** [comment]
hmm, do you maybe know what the problems were?

did install the 3.0.5 package and then 3.0.6 but didn't notice a problem at that time.

**Comment by jojo12** [comment]
Because I was on a special pc where I didn't find the printscreen, I can't reproduce the notices.

I tried to update now an other site with JEM 3.0.5 to JEM 3.0.6.
Installation ok, no error notices.
But now, when I go to the event details, I get
0 - DateTime::__construct(): Failed to parse time string (Di, 20. Januar 2015 19.30) at position 0 (D): The timezone could not be found in the database:

**Comment by jojo12** [comment]
Then I opened in backend an existing event and wanted to save it again:
I got:
Notice: Array to string conversion in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/models/fields/categoryedit.php on line 231

Notice: Array to string conversion in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/models/fields/categoryedit.php on line 238

Notice: Array to string conversion in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/models/fields/categoryedit.php on line 231

Notice: Array to string conversion in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/models/fields/categoryedit.php on line 238

Notice: Array to string conversion in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/models/fields/categoryedit.php on line 231

Notice: Array to string conversion in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/models/fields/categoryedit.php on line 238

Notice: Array to string conversion in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/models/fields/categoryedit.php on line 231

Notice: Array to string conversion in /srv/www/vhosts/mysite.ch.ch/httpdocs/administrator/components/com_jem/models/fields/categoryedit.php on line 238

Notice: Array to string conversion in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/models/fields/categoryedit.php on line 231

Notice: Array to string conversion in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/models/fields/categoryedit.php on line 238

and in red:

Fehler

Speichern fehlgeschlagen! Fehler: Unknown column 'startDateTime' in 'field list' SQL=UPDATE `xf910_jem_events` SET `locid`='5',`dates`='2015-01-20',`enddates`=NULL,`times`='14:30',`endtimes`='16:30',`title`='Kreistänze für Senioren',`alias`='kreistaenze-fuer-senioren',`created_by`='784',`modified`='2015-01-13 09:13:16',`modified_by`='784',`version`='42',`author_ip`='',`created`='2014-04-24 15:52:36',`introtext`='',`meta_keywords`='times',`meta_description`='DieVeranstaltungmitdemNamentitlebeginntamdatesumtimesina_name.',`recurrence_first_id`='0',`recurrence_interval`='',`recurrence_type`='0',`recurrence_counter`='0',`recurrence_limit`='0',`recurrence_limit_date`=NULL,`recurrence_byday`=NULL,`datimage`='images/PIK_VT.jpg',`checked_out`='784',`checked_out_time`='2015-01-13 09:13:04',`registra`='0',`unregistra`='0',`maxplaces`='1',`waitinglist`='0',`hits`='351',`published`='1',`contactid`='1',`custom1`='',`custom2`='',`custom3`='',`custom4`='',`custom5`='',`custom6`='',`custom7`='',`custom8`='',`custom9`='',`custom10`='',`fulltext`='',`created_by_alias`='',`access`='1',`metadata`='{\"robots\":\"\",\"author\":\"\",\"rights\":\"\"}',`featured`='0',`attribs`='{\"event_show_author\":\"\",\"event_show_contact\":\"\",\"event_link_contact\":\"\",\"event_show_name_attendee\":\"\",\"event_attendeelist_visiblefor\":\"\",\"event_show_hits\":\"\",\"event_show_print_icon\":\"\",\"event_show_email_icon\":\"\",\"event_show_ical_icon\":\"\",\"event_show_detailstitle\":\"\",\"event_show_locdescription\":\"\",\"event_show_detailsadress\":\"\",\"event_show_detlinkvenue\":\"\",\"event_show_mapserv\":\"\",\"event_comunsolution\":\"\",\"event_comunoption\":\"\",\"event_show_description\":\"\"}',`language`='',`recurrence_group`='',`recurrence_until`='',`recurrence_freq`='',`wholeday`='',`recurrence_count`='',`recurrence_weekday`='',`mailing`='',`opendate`='0',`startDateTime`='2015-01-20 14:30:00',`endDateTime`='2015-01-20 16:30:00' WHERE `id`='119'

**Comment by jojo12** [comment]
In the site, I installed JEM3.0.6 on a cleaned and imported CSV files, this doesn't happen.

**Comment by jojo12** [comment]
I tried to export/import the events to CSV.
Importing I got the notice:
1054 Unknown column 'startDateTime' in 'field list' SQL=INSERT IGNORE INTO `xf910_jem_events` (`id`,`locid`,`dates`,`enddates`,`title`,`alias`,`created_by`,`modified`,`modified_by`,`version`,`author_ip`,`created`,`introtext`,`meta_keywords`,`meta_description`,`recurrence_first_id`,`recurrence_interval`,`recurrence_type`,`recurrence_counter`,`recurrence_limit`,`recurrence_byday`,`datimage`,`checked_out`,`checked_out_time`,`registra`,`unregistra`,`maxplaces`,`waitinglist`,`hits`,`published`,`contactid`,`custom1`,`custom2`,`custom3`,`custom4`,`custom5`,`custom6`,`custom7`,`custom8`,`custom9`,`custom10`,`fulltext`,`created_by_alias`,`access`,`metadata`,`featured`,`attribs`,`language`,`recurrence_group`,`recurrence_until`,`recurrence_freq`,`wholeday`,`recurrence_count`,`recurrence_weekday`,`mailing`,`opendate`,`startDateTime`,`endDateTime`) VALUES ('48','0','2014-07-08','2014-08-17','Ferienpause','ferienpause','784','2014-09-24 17:09:11','784','9','','2014-06-12 21:25:01','','titlea_namedatestimes','DieVeranstaltungmitdemNamentitlebeginntamdatesumtimesina_name.','0','0','0','0','0','','','0','0000-00-00 00:00:00','0','0','0','0','2323','2','1','','','','','','','','','','','','','1','{\"robots\":\"\",\"author\":\"\",\"rights\":\"\"}','0','{\"event_show_author\":\"\",\"event_link_author\":\"\",\"event_show_contact\":\"\",\"event_link_contact\":\"\",\"event_show_hits\":\"\",\"event_show_print_icon\":\"\",\"event_show_email_icon\":\"\",\"event_show_ical_icon\":\"\",\"event_show_detailstitle\":\"\",\"event_show_locdescription\":\"\",\"event_show_detailsadress\":\"\",\"event_show_detlinkvenue\":\"\",\"event_show_mapserv\":\"\",\"event_tld\":\"\",\"event_lg\":\"\",\"event_comunsolution\":\"\",\"event_comunoption\":\"\",\"event_show_description\":\"\"}','','','','','','0','','','0','2014-07-08 00:00:00','2014-08-17 00:00:00')

**Comment by JKoelman** [comment]
> But now, when I go to the event details, I get
0 - DateTime::__construct(): Failed to parse time string (Di, 20. Januar 2015 19.30) at position 0 (D): The timezone could not be found in the database:

that's right there was a problem with the date function but should be ok now.
--> did remove the release for now but the files at Github have been updated.



> Importing I got the notice:
1054 Unknown column 'startDateTime'

not sure why you got that notice as that field/column "startDateTime" should have been created during install. it was added since pkg 3.0.3 and was also in the update sql.  perhaps you installed a dev version where the fields weren't added at the time before release.

**Comment by JKoelman** [comment]
will test out the update from pkg 3.0.2 to pkg 3.0.6 and see what happens.

**Comment by jojo12** [comment]
it seems, this new fields in db were not created: startDateTime, endDateTime, note

**Comment by jojo12** [comment]
after manually inserting of these 3 fields, rests only the
 when I go to the event details, I get
0 - DateTime::__construct(): Failed to parse time string (Di, 20. Januar 2015 19.30) at position 0 (D): The timezone could not be found in the database:

**Comment by JKoelman** [comment]
> it seems, this new fields in db were not created: startDateTime, endDateTime, note

in that case the update 3.0.3 didn't run and it might have been that you had a pre-release version installed at that time.

> 0 - DateTime::__construct():
the problem was also posted in the forum, but was resolved by the updated code. or did you install the recent files from the dev branche?

**Comment by JKoelman** [comment]
did install pkg 3.0.2, loaded sampledata and then installed pkg 3.0.6

Am not experiencing the error you mentioned and did see the fields/columns were created.
so at the moment i can't replicate the problem.

// sidenote: maybe we should output the error notices more friendly

**Comment by JKoelman** [comment]
i think you know but you can download the dev-branch over here:  https://github.com/jemproject/JEM-3/archive/dev.zip

**Comment by jojo12** [comment]
@bluefox: sorry, it must be my bad english. I appreciate your work. I  never want to output something unfriendly.

**Comment by JKoelman** [comment]
uhm, thing you understood me incorrectly.
the thing is that when running into a query error you're getting a white screen and maybe we should prevent that.

**Comment by JKoelman** [comment]
hi Jojo,.   question: did you resolve the problem with date within the event-view?

**Comment by jojo12** [comment]
I uninstalled the JEM with the new cleanup. And then installed totally new the JEM 3.0.6. After I imported the events, categories and venues via CSV. Like that the site works fine.

**Comment by JKoelman** [comment]
yeah am also happy with that option..  think i'll test the package a bit more in the weekend and then make a release so other people can test it out too.
