### ISSUE TITLE
new cb plugins in cb 2.0.4: ok

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#213]
Hi,
I just tried the changes in the cb plugins with cb 2.0. 
Before they worked, but there was a brown triangle, to show it's not totally compatible.
Now it's all green, means ok!
Bravo!
I cannot try this: is this new version compatible with the old cb 1.9.1 too, or do we need to give different versions?

**Comment by JKoelman** [comment]
the reason that the brown triangle disappeard has probably to do that i changed the version nr in the xml to 2.0.4  doing so it probably won't install within CB1.9 so that's going to be a problem.

**Comment by Hoffi1** [comment]
Yep, both(!) version numbers must stay on 1.9.
(with JEM 2.0.x I tried to set <version>2.0 to be conform to JEM but it worked)
Maybe the CB guys can give us a hint?
