### ISSUE TITLE
v3.0.6 alpha installed ok

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#215]
i've also seen, the notice, if you try to update from 2.1.1.
It's possible to import the exported files from 2.1.1.

**Comment by JKoelman** [comment]
thx Jojo,

about the notice:
did add the notice just to avoid unwanted things for now, maybe the description needs to change a bit not sure. the check is within the package and not within com_jem but as most people will install the package i think it's good for now.

and for the rest it's like the previous JEM3.0.6 as not much has been changed.

**Comment by jojo12** [comment]
yes, I know: I just made yesterday a package from the dev. So it's just a bit longer I try (and test)
it's just more than an alpha, I  am sure.
(and with importing CSV files which are exported in JEM 2.1.1) you can migrate very easy.
