### ISSUE TITLE
bug:  frontend eventedit, blank modal when looking for a venue

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#224]
I have a lot of venues in JEM 3.0.6 (imported from JEM 2.1.1.)
 In backend all is ok. 
In Frontend when I want to add an existing venue to the event, I  get a modal page with no venue inside.
The same in backend is ok.

**Comment by JKoelman** [comment]
maybe it has to do with the setting "own venues"..
settings-> tab "view" -> tab "editevent"

**Comment by jojo12** [comment]
if yes then it would be >settings >userrights> eigene Orte editieren
there is no such in settings views editevent

but i can choose there yes or no, it's always the same bug!

**Comment by JKoelman** [comment]
hmm, there should be an option within editevent

![clipboard04](https://cloud.githubusercontent.com/assets/2514855/5838329/f520bfbc-a186-11e4-8220-31e7d6ba492b.jpg)

**Comment by jojo12** [comment]
strange, my view in JEM 3.0.6 is:
![strangeview](https://cloud.githubusercontent.com/assets/2960236/5838511/3730fccc-a188-11e4-835c-3459b1a38207.png)

**Comment by jojo12** [comment]
oh, sorry, it's the first point. I will try more.

**Comment by jojo12** [comment]
can be closed
