### ISSUE TITLE
why you take away the $levels = $user->getAuthorisedViewLevels(); ?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#229]
Hi, I've just seen, that you take away this.
I thought, this is important for the view access rights

**Comment by JKoelman** [comment]
if you're talking about the change in the modules: https://github.com/jemproject/JEM-3/commit/455fa68f30d112a37cbd74591456e5bba4d1af1b  then the following:

$levels is indeed important but the variable defined in the module is not used anymore. Instead the access/view rights are defined in the central eventslist-model.

**Comment by jojo12** [comment]
Thanks. Was important for me to understand!

**Comment by JKoelman** [comment]
can understand that,..  will close the issue as it's been answered
