### ISSUE TITLE
FR: make acceslevel for attachments multi-select

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-3#236]
At the moment it's possible to select 1 value for accesslevel but would say it's better to make it a multi-select this way we don't have to add the attachment again to make it visible for a different view-level.

**Comment by JKoelman** [comment]
did see that the fields for attachments are not form fields but it can be adjusted by adding them to the xml and some other actions.

**Comment by Hoffi1** [comment]
No good idea, I think. In Joomla each thing can have exactly one access level. So why leaving this established way and struggling through the jungle?

**Comment by JKoelman** [comment]
alright then won't change it then but then it's better to make it a dropdown so it's clear that only 1 value can be selected.

**Comment by Hoffi1** [comment]
Yes, normally it's a dropdown. Then it would be useful to change layout to normal form, meaning all four fields (File, Name, Description, Access) among each other with label left, field right beside.

**Comment by JKoelman** [comment]
about changing it to dropdown:  as a size was added the dropdown is not there but will set it back to size="1" so it wil show like the image.

![clipboard03](https://cloud.githubusercontent.com/assets/2514855/6094368/f18b755a-af27-11e4-8461-71751aaec538.jpg)
