### ISSUE TITLE
JEM 3.0.7 no venue in choosevenue window

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#254]
I installed JEM 3.0.7 on a clean Joomla 3.4 (with extension installer patch)
when creating event there is no venue in choosevenue modal window.
But in choosecontact modal window there is a contacdt (I have only one)

**Comment by JKoelman** [comment]
did you enable "show own venues" ?

**Comment by jojo12** [comment]
can you help me? I don't find it anymore in the settings!

**Comment by JKoelman** [comment]
it should be in Settings-view - tab editevent - owned venues

did set the default to 0 in the recent commits so you won't run into this issue in new releases.

**Comment by jojo12** [comment]
That's it, I found it disabled it, and now all the venues are there too! Thanks. Can be closed
