### ISSUE TITLE
for Joomla 3.4+: use sidebar hide in backend

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#255]
in Joomla 3.4 there is the possibility to hide the sidebar in backend. Would be nice to add this!

**Comment by JKoelman** [comment]
something like this? 
![clipboard01](https://cloud.githubusercontent.com/assets/2514855/6426688/4deb28c2-bf68-11e4-916c-d0cecfba63f3.jpg)

can be done.

**Comment by jojo12** [comment]
yes, it has time, but it's good to use features joomla 3.4 offers!

**Comment by JKoelman** [comment]
sidebar has been added so will close this issue
