### ISSUE TITLE
error notice with listevents

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#257]
Hi I installed from dev the listevents plugin in JEM 3.0.7 and Joomla 4.3 clean
I got the following error notices:
Warning: require_once(/srv/www/vhosts/mysite.ch/httpdocs/components/com_jem/helpers/helper.php): failed to open stream: No such file or directory in /srv/www/vhosts/mysite.ch/httpdocs/plugins/content/listevents/listevents.php on line 12

Fatal error: require_once(): Failed opening required '/srv/www/vhosts/mysite.ch/httpdocs/components/com_jem/helpers/helper.php' (include_path='.:') in /srv/www/vhosts/mysite.ch/httpdocs/plugins/content/listevents/listevents.php on line 12

**Comment by Hoffi1** [comment]
I don't try to ask but have you uninstalled the component?
For me the path looks ok and there should be a helper.php if com_jem is installed.

Maybe the plugin should be more tolerant and use include:once and return if JemHelper class is not loaded.

**Comment by jojo12** [comment]
during installation something was really strange.
now it seems to work ok

**Comment by JKoelman** [comment]
@jojo12 can try it out but will be somewhere in the weekend.
also be aware that the files in the dev-branch will be updated a lot more soon.

**Comment by JKoelman** [comment]
did try it out by installing the plugin but am not seeing a strange notice so not sure what might have happened.
