### ISSUE TITLE
Table Event not supported

### ISSUE THREAD

**Issue by jaanusnurmoja** [jemproject/JEM-3#258]
Something raises error
Table Event not supported. File not found.
when I save the event in frontend. 
(JLIB_APPLICATION_ERROR_TABLE_NAME_NOT_SUPPORTED)

**Comment by JKoelman** [comment]
am wondering:
- was it a clean install?

when saving it will detect thew table file located in /administrator/components/tables
- what's the name of your file for the events?
- how is the class named in that file?
```class ....?..... extends JTable```

when it's taking from JEM2 then that can be a problem.

**Comment by jaanusnurmoja** [comment]
class JemTableEvents extends JTable
file name is events.php 
Like it should be?

**Comment by jaanusnurmoja** [comment]
BTW it occurs also on load and only in details view (not in form view)

**Comment by Hoffi1** [comment]
Hm... I wonder about the word ```event``` without an ```s``` in the first post.

**Comment by jaanusnurmoja** [comment]
Just a moment, will see what happens if I set the frontend lang to English

**Comment by JKoelman** [comment]
the files seems to be ok but then i'm wondering:
-- are there plugins running in the background?

maybe there is error note in the logfile, but as the site is on the net that can be a bit tricky to find out.
Did also see there was a TypeError (form is not recognized) but that's not causing the problem you noticed.

**Comment by jaanusnurmoja** [comment]
and that TypeError is not caused by JEM

**Comment by JKoelman** [comment]
> and that TypeError is not caused by JEM

i know it's caused by somethign else but wanted to drop the note. But am wondering if you do have some plugins running in the backend that are calling the event table.  

did install the JEM 3.0.7 component but am not seeing the problem at the moment but will check some more.

**Comment by JKoelman** [comment]
or it can be some code in the view.html.php that's calling a function where the "event" table is called instead of "events"  and that's why io was wondering if it's a clean install or a modified one.

if modified it could be related to some of that code.

**Comment by jaanusnurmoja** [comment]
JTable::getInstance('Event', 'JEMTable'); - under views/event ?

**Comment by jaanusnurmoja** [comment]
Not clean install. Earlier github->pc->ftp, the latest: 307 installed over 306

Yes, a content plugin is running in background but removing it didn't help. And the thing that is running with content plugin are using partially the data from JEM tables (Fabrik list), but I don't see any reason why it should use JEM code as it uses Fabrik code

**Comment by JKoelman** [comment]
> JTable::getInstance('Event', 'JEMTable'); - under views/event ?

i meant a call in view.html.php to a function in the model file. In that model file can be a function that's calling the table file. but if it's install on top the files should be overwritten and the problem would not be there. can say that i'm not seeing the issue with a clean install of JEM 3.0.7 so can't replicate it.  Do you have template overrides?

**Comment by jaanusnurmoja** [comment]
Perhaps this help somehow:
the message disappeared when I renamed administrator/components/com_jem/tables/events.php to event.php and also its classname (removed 's' from Events) .
Nothing else happened but when tried to edit event, then got:
`Fatal error: Call to a member function getKeyName() on a non-object in /home/..../libraries/legacy/controller/form.php on line 373`

**Comment by JKoelman** [comment]
> the message disappeared 
and that can be correct as you're creating a file that is expected by the function that's looking for that file. but when going to editevent JEM wants to work with the events table file and will say that it can't find it (fatal error)

maybe the easiest for you is to copy/add the table file for now (event + events) this way you can try to locate the problem but in the front the problem is not there anymore.

**Comment by jaanusnurmoja** [comment]
thanks, interesting idea, will try :)

**Comment by JKoelman** [comment]
hmm, did install JEM and removed the table file to see if it would give a error notice in the detail view but it was not giving the problem you mentioned..

**Comment by jaanusnurmoja** [comment]
then no idea ... perhaps I should push my code in its current state to my github and compare with original. To find some possible forgotten customisations. 

BTW, anyway I have an intention to make one PR. Not any fix but new feature.

**Comment by jaanusnurmoja** [comment]
https://github.com/jemproject/JEM-3/compare/master...jaanusnurmoja:compare

Well, couple of modal files... Could there be something?

**Comment by JKoelman** [comment]
the files look fine so would say the problem is not in there..

**Comment by jaanusnurmoja** [comment]
Could it be that some other event management component that I have installed generates this false alert?

**Comment by JKoelman** [comment]
question: are you still having a problem with it or did you manage to resolve it?

**Comment by jaanusnurmoja** [comment]
Unfortunately the issue is still present

**Comment by JKoelman** [comment]
just wondering: 

Can it be related to com_fabrik/com_fabrik plugin or something like that. that there is somewhere a call to the Event table. ```JTable::getInstance('Event'); ```

**Comment by jaanusnurmoja** [comment]
Ah, I thought about the possibility that it could be related to the Fabrik because some of its list views are showing data from jem tables. Although the warning is displayed also when the event doesn't display the Fabrik list. Will look at the Fabrik code.

**Comment by jaanusnurmoja** [comment]
FOUND! The issue was caused by DP Attachments component. When I turned it off, the message disappeared.

**Comment by JKoelman** [comment]
ah good to know what was causing it.

**Comment by JKoelman** [comment]
just to note:  if you need the attachments component in the content pages then you can adapt the code so it can be run without trowing in the error.

**Comment by jaanusnurmoja** [comment]
OK, how?

**Comment by JKoelman** [comment]
> OK, how

Have to dive into it but one way can be to tweak that library/core.php file.
We can define a new table name ('Events') in there and doing so will give the option to upload attachments but it will have issues as removal of the file isn't working.

so maybe it's possible to adapt things to make it check at the context and if it's dealing with com_jem it will return false.

**Comment by JKoelman** [comment]
within the plugin: plugins/content/dpattachments/dpattachments.php we can enter code like this in the functions.  

```if ($context == 'com_jem.event') {
			return false;
		}
		```
in case of the event-view of JEM it will return false but it will function in the Joomla content view.
To have the attachments option to be fully working with JEM we've to alter more code but won't dive into it for a while.

**Comment by jaanusnurmoja** [comment]
Thanks, it works! But still strange that such false warning appears.
BTW - doesn't JEM have its own attachment feature?

**Comment by JKoelman** [comment]
> But still strange that such false warning appears
it can happen..  The thing is that they are looking at the name of the model, for the Article they do define a new name in core.php (Content) and doing so there is no problem but they can't do that for every component.

> BTW - doesn't JEM have its own attachment feature?
yes, aldo it's not totally perfect.

**Comment by laoneo** [comment]
I've added a commit which will eliminate the warning https://github.com/Digital-Peak/DPAttachments/issues/6#issuecomment-96959923.

**Comment by JKoelman** [comment]
thx
