### ISSUE TITLE
submit an event as guest: no new venue possible

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#261]
Hi,
when I want to submit an event as guest (it's enabled in the settings), I can only use existing venues in the modal window.
When I try to submit a new venue, it's said, you are not allowed to do that without login.

If this is wanted it's really ok, but it's important to know.

(BTW: the new recaptcha 2.0 works best in this window)

**Comment by JKoelman** [comment]
hi Jojo,  it was inteded like that.  The thing is that there have been changes in editevent but noit in editvenue. In the backend it also states "AC-Events" but maybe it can be changed later.

**Comment by jojo12** [comment]
Thanks for your answer.
