### ISSUE TITLE
mod_jem_banner: integrate in JEM 3.0.8

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#262]
Hi,
in my JEM 3.0.7 mod_jem_banner works fine. So it would be nice to integrate it.

**Comment by JKoelman** [comment]
can be done, it will be something like:
- upload files to github (module folder)
- update files to J3 standard
- adapt package files
- etc...  
maybe something for next week.

**Comment by JKoelman** [comment]
will add the module so am closing the issue
