### ISSUE TITLE
message around waiting list in backend

### ISSUE THREAD

**Issue by cn-tools** [jemproject/JEM-3#265]
i'm not sure, but i think in file "admin/controllers/attendees.php" in line 136 (and maybe some other files/lines), you use the wrong language const for the info message after the click.

**Comment by JKoelman** [comment]
sorry for the late response (currently spending time to other things) but you're right there is something wrong there so will try to fix it.

**Comment by cn-tools** [comment]
no problem ;)

now i have searched for any other places, so i found the same problem in "site/controllers/attendees.php" at line 88.

**Comment by JKoelman** [comment]
thx, will change it there too :)
