### ISSUE TITLE
error notice after installing 3.0.7 dev 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#272]
Hi, I installed, and imported CSV files
when not logged in, i had a nice simple list,
then I logged in as superuser and had this problem:

Unknown column 'gr.edit' in 'where clause' SQL=SELECT gr.id FROM `vyx60_jem_groups` AS gr LEFT JOIN vyx60_jem_groupmembers AS g ON g.group_id = gr.id WHERE g.member = 236 AND `gr`.`edit` =1 AND g.member NOT LIKE 0

**Comment by Hoffi1** [comment]
Shouldn't it be 'editevent' or 'editvenue' instead of 'edit'?
Also the complete query seems to be not required because a Superuser has licence to edit all...

But think it's intermediate code where @JKoelman is currently working on so I woun't look. deeper into yet.

**Comment by JKoelman** [comment]
it's indeed code that's not finished and have to finish it sometime and that will be soon.

**Comment by JKoelman** [comment]
not sure in what view you noticed the error @jojo12  but will close this issue.
