### ISSUE TITLE
ajax calendar module works fine!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-3#274]
works fine. Nice to have!

**Comment by JKoelman** [comment]
actually am having issue with the language..

Did set the frontend language to Dutch and noticed that at first load the language was ok but after pressing the next month the language did change to English. think it happens as it's calling the ajaxloader page but that's something to sort out..

**Comment by jojo12** [comment]
didn't try it with the language.

**Comment by JKoelman** [comment]
will try to sort out the language problem soon :)

**Comment by JKoelman** [comment]
will close this one as the language should be ok, maybe some options should be tweaked but that's for later.
