### ISSUE TITLE
Event-page: include event "AfterdisplayContent"

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-3#275]
this way it's possible for plugins to do some actions with it.

**Comment by JKoelman** [comment]
ofcourse we could add some additional events

**Comment by cn-tools** [comment]
the event "onContentAfterTitle" is triggered in "site/views/event/view.html.php", but the text isn't used

**Comment by JKoelman** [comment]
maybe it's better to strip that "event" but was wondering if we should have some more event in that page.

we also have a "onEventEnd" that's called before the ical-icon and is used for displaying JComments

**Comment by JKoelman** [comment]
will close this issue for now..  If we need other events later in the event-view then a new issue can be created.
